// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Mutex is an autogenerated mock type for the Mutex type
type Mutex struct {
	mock.Mock
}

// Lock provides a mock function with no fields
func (_m *Mutex) Lock() {
	_m.Called()
}

// Unlock provides a mock function with no fields
func (_m *Mutex) Unlock() {
	_m.Called()
}

// NewMutex creates a new instance of Mutex. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMutex(t interface {
	mock.TestingT
	Cleanup(func())
}) *Mutex {
	mock := &Mutex{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
