// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Seat is an autogenerated mock type for the Seat type
type Seat struct {
	mock.Mock
}

// GetSpecial provides a mock function with no fields
func (_m *Seat) GetSpecial() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetSpecial")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// IsBookedSeat provides a mock function with no fields
func (_m *Seat) IsBookedSeat() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsBookedSeat")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// SetBooked provides a mock function with given fields: _a0
func (_m *Seat) SetBooked(_a0 bool) {
	_m.Called(_a0)
}

// NewSeat creates a new instance of Seat. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSeat(t interface {
	mock.TestingT
	Cleanup(func())
}) *Seat {
	mock := &Seat{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
